version: "3.9"
services:
    app:
        container_name: mebel-pepak
        env_file:
            - .env
        restart: always
        build:
            context: .
            target: php
            args:
                - APP_NAME=${APP_NAME}
                - APP_ENV=${APP_ENV}
        working_dir: /var/www/${APP_NAME}
        volumes:
            - ./:/var/www/${APP_NAME}
        ports:
            - '8002:80'
        networks:
            - env-server
        healthcheck:
            test: ["CMD-SHELL", "curl -f http://localhost:8002 || exit 1"]
            interval: 30s
            timeout: 10s
            retries: 3
networks:
    env-server:
        name: ${NETWORK_NAME}
        driver: bridge
        external: true
